// Auto-generated by process_enemy_frames.py
window.MONSTER2_IMG = {};
window._monster2Loaded = false;

const MONSTER2_FRAME_COUNT = {
  atk: 76,
  run: 27
};

function loadMonster2Frames(onReady){
  const base = 'enemies/monster2_frames';
  const keys = Object.keys(MONSTER2_FRAME_COUNT);
  let total = 0;
  for(const k of keys) total += MONSTER2_FRAME_COUNT[k];
  let loaded = 0;
  console.log('[monster2] loading', total, 'frames');

  function done(){
    if(++loaded >= total){
      window._monster2Loaded = true;
      console.log('[monster2] all frames loaded');
      if(onReady) onReady();
    }
  }

  for(const key of keys){
    MONSTER2_IMG[key] = [];
    const cnt = MONSTER2_FRAME_COUNT[key];
    for(let i = 0; i < cnt; i++){
      const img = new Image();
      const idx = String(i).padStart(2, '0');
      const _i = i, _key = key;
      img.onload  = function(){ MONSTER2_IMG[_key][_i] = this; done(); };
      img.onerror = function(){ MONSTER2_IMG[_key][_i] = null;  done(); };
      img.src = base + '/' + key + '/' + key + '_' + idx + '.png';
    }
  }
}

window.loadMonster2Frames = loadMonster2Frames;
