// Auto-generated by process_enemy_frames.py
window.MONSTER3_IMG = {};
window._monster3Loaded = false;

const MONSTER3_FRAME_COUNT = {
  atk: 40,
  run: 30
};

function loadMonster3Frames(onReady){
  const base = 'enemies/monster3_frames';
  const keys = Object.keys(MONSTER3_FRAME_COUNT);
  let total = 0;
  for(const k of keys) total += MONSTER3_FRAME_COUNT[k];
  let loaded = 0;
  console.log('[monster3] loading', total, 'frames');

  function done(){
    if(++loaded >= total){
      window._monster3Loaded = true;
      console.log('[monster3] all frames loaded');
      if(onReady) onReady();
    }
  }

  for(const key of keys){
    MONSTER3_IMG[key] = [];
    const cnt = MONSTER3_FRAME_COUNT[key];
    for(let i = 0; i < cnt; i++){
      const img = new Image();
      const idx = String(i).padStart(2, '0');
      const _i = i, _key = key;
      img.onload  = function(){ MONSTER3_IMG[_key][_i] = this; done(); };
      img.onerror = function(){ MONSTER3_IMG[_key][_i] = null;  done(); };
      img.src = base + '/' + key + '/' + key + '_' + idx + '.png';
    }
  }
}

window.loadMonster3Frames = loadMonster3Frames;
