// Auto-generated by process_enemy_frames.py
window.MONSTER1_IMG = {};
window._monster1Loaded = false;

const MONSTER1_FRAME_COUNT = {
  atk: 28,
  run: 36
};

function loadMonster1Frames(onReady){
  const base = 'enemies/monster1_frames';
  const keys = Object.keys(MONSTER1_FRAME_COUNT);
  let total = 0;
  for(const k of keys) total += MONSTER1_FRAME_COUNT[k];
  let loaded = 0;
  console.log('[monster1] loading', total, 'frames');

  function done(){
    if(++loaded >= total){
      window._monster1Loaded = true;
      console.log('[monster1] all frames loaded');
      if(onReady) onReady();
    }
  }

  for(const key of keys){
    MONSTER1_IMG[key] = [];
    const cnt = MONSTER1_FRAME_COUNT[key];
    for(let i = 0; i < cnt; i++){
      const img = new Image();
      const idx = String(i).padStart(2, '0');
      const _i = i, _key = key;
      img.onload  = function(){ MONSTER1_IMG[_key][_i] = this; done(); };
      img.onerror = function(){ MONSTER1_IMG[_key][_i] = null;  done(); };
      img.src = base + '/' + key + '/' + key + '_' + idx + '.png';
    }
  }
}

window.loadMonster1Frames = loadMonster1Frames;
